# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
let
  zfsMountConfig = name: { 
    device = name;
    fsType = "zfs";
    options = [ "nofail" ];
  };
in
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix") 
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "sd_mod" "igb" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "zram" ];
  boot.extraModulePackages = [ ];

  fileSystems = {
      #Primary File Systems
      "/boot" = { 
        device = "/dev/disk/by-uuid/9FE7-0CB3";
        fsType = "vfat";
      };

      "/" = {
        device = "zroot/nixos";
        fsType = "zfs";
      };

      "/nix" = {
        device = "zroot/nixos/store";
        fsType = "zfs";
      };

      # ZStorage File Systems
      "/home" = zfsMountConfig "zstorage/home";
      "/var/backup" = zfsMountConfig "zstorage/backups";
      "/var/lib/pterodactyl/volumes" = zfsMountConfig "zstorage/pterodactyl";
      "/var/lib/verdaccio/storage" = zfsMountConfig "zstorage/services/verdaccio";
      "/var/lib/nextcloud" = zfsMountConfig "zstorage/services/nextcloud";

      # ZRoot File Systems
      "/var/lib/docker" = zfsMountConfig "zroot/docker";
      "/var/lib/mysql" = zfsMountConfig "zroot/services/mysql";
      "/var/lib/pterodactyl" = zfsMountConfig "zroot/services/pterodactyl";
      "/var/lib/verdaccio" = zfsMountConfig "zroot/services/verdaccio";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/633a5292-fd4d-4fef-8b44-7f39c3bc9f4c"; }
  ];

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
