{ pkgs, lib, config, ... }:
let
  cfg = config.local.zfs;

  serviceConfig = {
    after = [ "zfs.target" ];
    restartIfChanged = false;
    path = [ config.boot.zfs.package ];
    serviceConfig.Type = "oneshot";
  };

  # Although this script is technically impure, we use
  # runCommandLocal to help guarantee a unique entry per host.
  # Technically if you build a closure and then copy to a remote
  # host it wouldn't be unique, but that's something I'm unlikely
  # to do right now.
  defaultHostKey = pkgs.runCommandLocal "initrd-host-keys"
    {
      buildInputs = [ pkgs.openssh ];
    } ''
    ssh-keygen \
      -t ed25519 \
      -f initrd_key \
      -C "Initrd host key generated by NixOS" \
      -N ""
    mv initrd_key $out
  '';
in {
  options.local.zfs.encryptedDatasets = lib.mkOption {
    type = lib.types.listOf lib.types.str;
    default = [ ];
    description = "ZFS datasets that should be unlocked in initrd.";
  };

  options.local.zfs.initrdHostKey = lib.mkOption {
    type = lib.types.path;
    default = defaultHostKey;
    # Set defaultText so we don't inadvertently load the file into the store when reading docs.
    defaultText = "Generated at build time";
    description = "Private key to use for the initrd SSH server";
  };

  config = {

    boot.supportedFilesystems = [ "zfs" ];

    boot.zfs = {
      package = pkgs.zfs_unstable;
      forceImportRoot = true;
      forceImportAll = false;
    };

    boot.extraModprobeConfig = ''
      options zfs zfs_scrub_min_time_ms=50
      options zfs zfs_arc_max=4294967296
    '';

    # Set up initrd unlocker system
    boot.initrd = lib.mkIf (cfg.encryptedDatasets != [ ]) {
      network.ssh = {
        enable = true;
        port = 6416;
        authorizedKeys = config.users.users.root.openssh.authorizedKeys.keys;
        hostKeys = [ cfg.initrdHostKey ];
      };
    };

    # Incremental scrubbing to avoid drive murder
    systemd.services.zfs-scrub = serviceConfig // {
      description = "Start ZFS incremental scrub";
      script = "zpool scrub $(zpool list -Ho name)";
    };

    systemd.services.zfs-scrub-stop = serviceConfig // {
      description = "Stop ZFS incremental scrub";
      script = "zpool scrub -p $(zpool list -Ho name) || true";
    };

    systemd.timers.zfs-scrub = {
      description = "Start ZFS incremental scrub";
      wantedBy = [ "timers.target" ];
      after = [ "zfs.target" ];
      timerConfig = {
        OnCalendar = "*-*-* 05:00:00";
        RandomizedDelaySec = 60;
        Persistent = false;
      };
    };

    # Runs 30 minutes after the above, or on next boot
    systemd.timers.zfs-scrub-stop = {
      description = "Stop ZFS incremental scrub";
      wantedBy = [ "timers.target" ];
      after = [ "zfs.target" ];
      timerConfig = {
        OnCalendar = "*-*-* 05:30:00";
        RandomizedDelaySec = 60;
        Persistent = true;
      };
    };
  };
}
